# Generated by Django 4.2.4 on 2023-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdefinition',
            name='details_required',
        ),
        migrations.AddField(
            model_name='documentdefinition',
            name='details',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
